import RPi.GPIO as GPIO

MOTOR_CONTROL_PIN1 = 22
MOTOR_CONTROL_PIN2 = 23
MOTOR_PWM_PIN = 24

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(MOTOR_CONTROL_PIN1, GPIO.OUT)
GPIO.setup(MOTOR_CONTROL_PIN2, GPIO.OUT)
GPIO.setup(MOTOR_PWM_PIN, GPIO.OUT)

MOTER_PWM_FREQ = 1000
motor_pwm = GPIO.PWM(MOTOR_PWM_PIN, MOTER_PWM_FREQ)
motor_pwm.start(0)

GPIO.output(MOTOR_CONTROL_PIN1, False)
GPIO.output(MOTOR_CONTROL_PIN2, True)
motor_pwm.ChangeDutyCycle(50)